### ISSUE TITLE
agent正常发送数据，oap报错

### ISSUE THREAD

**Issue by arthron** [SkyAPM/SkyAPM-php-sdk#148]
agent每次发送数据时oap都报出以下异常
oap日志
Oct 21, 2019 3:49:07 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@2a7b3712
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onError(TraceSegmentReportServiceHandler.java:65)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

es中索引已建好，无数据

**Comment by lea21st** [comment]
解锁了吗，我也是

**Comment by arthron** [comment]
> 解决了吗，我也是

date一下看看

**Comment by heyanlong** [comment]
还没吧

**Comment by lea21st** [comment]
我用docker装的skywalking，可以；
