### ISSUE TITLE
请求apm.api:12800/instance/register抛出NPE异常

### ISSUE THREAD

**Issue by niko-liu** [SkyAPM/SkyAPM-php-sdk#159]
**Describe the bug**
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /instance/register. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NullPointerException
	at org.apache.skywalking.oap.server.receiver.register.provider.handler.v5.rest.InstanceDiscoveryServletHandler.doPost(InstanceDiscoveryServletHandler.java:81)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.doPost(JettyJsonHandler.java:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.skywalking.oap.server.library.server.jetty.JettyJsonHandler.service(JettyJsonHandler.java:105)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletH

**To Reproduce**

**Expected behavior**
php请求instance/register接口获取instanceid的时候出错

**Screenshots**

**PHP (please complete the following information):**
 - OS: Centos
 - Browser chrome
 - Version 7.x
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: Centos
 - Browser chrome
 - Version 6.5

**Additional context**

**Comment by niko-liu** [comment]
bak/SkyWalking.php的
$param  = array(
                'ai' => (int)$appId,
                'au' => $agentUuid,
                'rt' => $rt,
                'oi' => array(
                    'osName'    => PHP_OS,
                    'hostName'  => $hostname,
                    'processId' => $processNo,
                    'ipv4s'     => array($ip),
                ),
            );
hostName和processId两个参数名写错了，导致请求skywalking抛NPE，希望作者改一下代码。
另外这个代码里面生成traceid，跟skywalking上面看到的不一致

**Comment by niko-liu** [comment]
已解决

**Comment by heyanlong** [comment]
咋解决的啊
