### ISSUE TITLE
服务器内存资源持续增加，服务器高负载

### ISSUE THREAD

**Issue by WJC101** [SkyAPM/SkyAPM-php-sdk#211]
agent端报错:
![image](https://user-images.githubusercontent.com/51395991/77887745-b2989f00-729d-11ea-8ef9-3249975a03f0.png)
agent错误日志：
code = DeadlineExceeded desc = context deadline exceeded"

oap server报错：
![image](https://user-images.githubusercontent.com/51395991/77887810-d0660400-729d-11ea-8d9b-354eb337e65d.png)
oap server错误日志：
2020-03-30 15:44:49,134 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler - 64 [grpcServerPool-1-thread-18] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:517) ~[grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:738) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

现象：
go agent内存使用、主机负载会持续增长，直到内存耗完宕机

**Comment by heyanlong** [comment]
是agent发送的时候卡住了？

**Comment by WJC101** [comment]
找到疑似问题点了，我们这边的数据采集是自己写的埋点，因为用的是php5，不支持扩展。
问题可能出在数据采集的注册机制这块，采集端不停去注册，导致服务端崩溃




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"何延龙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 中午11:37
收件人:&nbsp;"SkyAPM/SkyAPM-php-sdk"<SkyAPM-php-sdk@noreply.github.com&gt;;
抄送:&nbsp;"王杰超"<360009334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 服务器内存资源持续增加，服务器高负载 (#211)





 
是agent发送的时候卡住了？

**Comment by heyanlong** [comment]
[黑人问号] 还能这么玩？自己埋点然后用go写的这个agent上报？
