### ISSUE TITLE
The MSYQL data store for OAP has a key duplicate problem in version 4.0

### ISSUE THREAD

**Issue by xinfeingxia85** [SkyAPM/SkyAPM-php-sdk#278]
The error log is as folows:

2020-10-19 16:22:17,090 - org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO -2797804 [DataCarrier.H2_ASYNCHRONOUS_BATCH_PERSISTENT.BulkConsumePool.0.Thread] ERROR [] - Duplicate entry '4d279223529947057d964c1af26df590' for key 'segment.PRIMARY'
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '4d279223529947057d964c1af26df590' for key 'segment.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.SQLExecutor.invoke(SQLExecutor.java:53) ~[storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO.synchronous(H2BatchDAO.java:72) [storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2BatchDAO$H2BatchConsumer.consume(H2BatchDAO.java:103) [storage-jdbc-hikaricp-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.consume(MultipleChannelsConsumer.java:79) [apm-datacarrier-8.1.0.jar:8.1.0]
	at org.apache.skywalking.apm.commons.datacarrier.consumer.MultipleChannelsConsumer.run(MultipleChannelsConsumer.java:50) [apm-datacarrier-8.1.0.jar:8.1.0]
### 

**Results:**
The effect is that there is very little data collection

**Runtime environment**
OS:   Ubuntu 18.04.1 LTS
OAP: 8.1.0 + msyql8.0
PHP: 7.1/7.3

 **Other instructions**
PHP7.1/7.3 runs on a physical machine.
PHP7.1 environment has many projects  in common, as does PHP7.3.

**Comment by wu-sheng** [comment]
Seems PHP(not java as the traceid format) agent generating duplicate segment id, somehow.

**Comment by heyanlong** [comment]
What is your request flow and topology?

**Comment by heyanlong** [comment]
`4d279223529947057d964c1af26df590` is not generated by php-sdk

**Comment by xinfeingxia85** [comment]
> What is your request flow and topology?

One machine runs two versions of PHP, 7.1 and 7.3, separate versions of the PHP process.
Versions 7.1 and 7.3 run different projects and call each other before each other. 
They are not independent PHP runtime environments for each project.

**Comment by xinfeingxia85** [comment]
@heyanlong 
After I used the SkyapM-PHp-sdK-fix-uuID branch, the database key duplication problem has been solved, but there is a new problem, which is an empty service name.  The data can be collected normally.

**The screenshot below:**
![image](https://user-images.githubusercontent.com/20057242/96536660-24cae280-12c7-11eb-9ed1-de014cc568ad.png)

**The error log for oap is as folows:**
2020-10-20 11:22:33,092 - org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker -297162 [pool-13-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.alarm.provider.NotifyHandler.notify(NotifyHandler.java:75) ~[server-alarm-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.alarm.AlarmEntrance.forward(AlarmEntrance.java:39) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:41) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.AlarmNotifyWorker.in(AlarmNotifyWorker.java:30) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.lambda$nextWorker$2(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.nextWorker(MetricsPersistentWorker.java:199) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.flushDataToStorage(MetricsPersistentWorker.java:178) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker.prepareBatch(MetricsPersistentWorker.java:146) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.analysis.worker.PersistenceWorker.buildBatchRequests(PersistenceWorker.java:74) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$extractDataAndSave$2(PersistenceTimer.java:107) ~[server-core-8.1.0.jar:8.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.extractDataAndSave(PersistenceTimer.java:102) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.core.storage.PersistenceTimer.lambda$start$0(PersistenceTimer.java:78) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.1.0.jar:8.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2020-10-20 11:22:50,993 - org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer -315063 [grpcServerPool-1-thread-2] ERROR [] - Can't split instance id into 2 parts, .1_
org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_
	at org.apache.skywalking.oap.server.core.analysis.IDManager$ServiceInstanceID.analysisId(IDManager.java:121) ~[server-core-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.MultiScopesAnalysisListener.parseExit(MultiScopesAnalysisListener.java:180) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.lambda$notifyExitListener$1(TraceAnalyzer.java:85) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.notifyExitListener(TraceAnalyzer.java:83) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.lambda$doAnalysis$0(TraceAnalyzer.java:61) ~[agent-analyzer-8.1.0.jar:8.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.doAnalysis(TraceAnalyzer.java:55) [agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.SegmentParserServiceImpl.send(SegmentParserServiceImpl.java:40) [agent-analyzer-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:73) [skywalking-trace-receiver-plugin-8.1.0.jar:8.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:64) [skywalking-trace-receiver-plugin-8.1.0.jar:8.1.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251) [grpc-stub-1.26.0.jar:1.26.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309) [grpc-core-1.26.0.jar:1.26.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292) [grpc-core-1.26.0.jar:1.26.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782) [grpc-core-1.26.0.jar:1.26.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.26.0.jar:1.26.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.26.0.jar:1.26.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by heyanlong** [comment]
Please provide /tmp/skywalking-php.log

**Comment by xinfeingxia85** [comment]
> Please provide /tmp/skywalking-php.log

**TraceId**: 14833685bb570678d596dc0be5768d87.10465.2912427867
**FIle**: 
[xx.log](https://github.com/SkyAPM/SkyAPM-php-sdk/files/5407563/xx.log)

**Comment by xinfeingxia85** [comment]
@heyanlong 
There are two aspects to the above problem：
1. The service name is null in some logs
2. There is a loss of data to the OAP
For example, the PHP log has two data traced through Traceid, but only one in the mysql store

**Comment by heyanlong** [comment]
Thanks report.

**Comment by heyanlong** [comment]
How is `service name is null` config？
e.g.
php.ini

**Comment by heyanlong** [comment]
Can you send WeChat to my mailbox?

**Comment by xinfeingxia85** [comment]
@heyanlong  OK。

As for the problem of empty Servicename, after I adjusted the number of bytes read, the empty situation only appeared when the content of the chain was very large, which was much less than the chance of 2048 before. The code is as follows:

```
[[noreturn]] void Manager::consumer(int *fd) {
    while (true) {
        char buffer[102400];
        int len = read(fd[0], buffer, 102400);
        if (len > 0) {
            pthread_mutex_lock(&mx);
            std::string msg(buffer, len);
            messageQueue.push(msg);
            pthread_mutex_unlock(&mx);

            pthread_mutex_lock(&cond_mx);
            pthread_cond_signal(&cond);
            pthread_mutex_unlock(&cond_mx);
        }
    }
}
```

**Comment by heyanlong** [comment]
Setting 102400 can solve the problem?

**Comment by xinfeingxia85** [comment]
The chances of servicename being empty are already small, almost non-existent.
I have debugged a lot of places where the problem should be Manager:: Consumer.
I'll keep watching tomorrow.

**Comment by xinfeingxia85** [comment]
@heyanlong  
WeChat has been sent to your github email address。
