### ISSUE TITLE
v4.1.1 Nothing send to Skywalking 8

### ISSUE THREAD

**Issue by ximply** [SkyAPM/SkyAPM-php-sdk#308]
No errors, but see nothing on Skywalking Web.

OS: Centos 6.4 X64, Linux 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
php:  PHP 7.1.10 (cli) (built: Oct 25 2017 22:57:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies

1. php.ini
[skywalking]
extension=/usr/local/php/lib/php/extensions/skywalking.so
; enable skywalking
skywalking.enable = 1
; Set skyWalking collector version (5 or 6 or 7 or 8)
skywalking.version = 8
; Set app code e.g. MyProjectName
skywalking.app_code = app-mobile
; Set grpc address
skywalking.grpc=192.168.10.211:11800
skywalking.log_enable=1

2./tmp/skywalking-php.log
the apache skywalking php plugin mounted
connect report service

3.conneted to skywalking
tcp        0      0 192.168.10.141:47064        192.168.10.211:11800        ESTABLISHED 
tcp        0      0 192.168.10.141:21242        192.168.10.211:11800        ESTABLISHED 
tcp        0      0 192.168.10.141:23910        192.168.10.211:11800        ESTABLISHED

**Comment by heyanlong** [comment]
Is there a request for the current service?

**Comment by ximply** [comment]
Yes, of course, I just upgrade from v3.3.2 to v4.1.1, it is ok when v3.3.2.

**Comment by heyanlong** [comment]
What information is in the log file?

**Comment by ximply** [comment]
1./tmp/skywalk-php.log nothing useful log.
2.our application log, a example josn format log
![image](https://user-images.githubusercontent.com/3693445/100354649-6a4b9f80-302b-11eb-9733-6b7eac8d0222.png)

**Comment by ximply** [comment]
Skywalking oap erro log:

2020-11-27 16:09:55,215 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler - 83 [grpcServerPool-1-thread-65] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.26.0.jar:1.26.0]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275) [grpc-stub-1.26.0.jar:1.26.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.26.0.jar:1.26.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.26.0.jar:1.26.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:867) [grpc-core-1.26.0.jar:1.26.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.26.0.jar:1.26.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.26.0.jar:1.26.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by heyanlong** [comment]
Need to confirm the running mode of php-fpm

**Comment by ximply** [comment]
static mode.

**Comment by ximply** [comment]
Use fastcgi.

**Comment by heyanlong** [comment]
daemonize `no` or `yes`?

**Comment by ximply** [comment]
default value, daemonize yes.

![Uploading image.png…]()

**Comment by heyanlong** [comment]
Maybe you can modify it to no.

**Comment by ximply** [comment]
But v3.3.2 is ok, why?

**Comment by heyanlong** [comment]
The technical implementation is somewhat different. v3.3.2 used unix socket.

**Comment by ximply** [comment]
Still nothing.

**Comment by ximply** [comment]
I just change daemonize to no, then run with: php-fpm  >/dev/null 2>&1 &

**Comment by heyanlong** [comment]
php-fpm --daemonize no > /dev/null 2>&1 &

**Comment by ximply** [comment]
It works now!  
![image](https://user-images.githubusercontent.com/3693445/101484937-5e4dcf00-3995-11eb-83e1-d63e92f032bf.png)
