### ISSUE TITLE
php进程崩溃core dump

### ISSUE THREAD

**Issue by Heimo-He** [SkyAPM/SkyAPM-php-sdk#332]
- os

centos7.9

- 内核

3.10.0-1160.11.1.el7.x86_64

- php

docker镜像 [php:7.2-fpm](https://hub.docker.com/layers/php/library/php/7.2-fpm/images/sha256-cde8c998f1d61d48b56a5f68b9af07737ace947a79a29febaac9b2e26d3d2490?context=explore)

- skywalking

[v4.1.1](https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.1.1.tar.gz)

安装编译参考[Dockerfile.7.2](https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile.7.2)

- php -i

```
skywalking
skywalking.app_code => xxx.php => xxx.php
skywalking.authentication => no value => no value
skywalking.enable => On => On
skywalking.grpc => xxx:11800 => xxx:11800
skywalking.grpc_tls_enable => 0 => 0
skywalking.grpc_tls_pem_cert_chain => no value => no value
skywalking.grpc_tls_pem_private_key => no value => no value
skywalking.grpc_tls_pem_root_certs => no value => no value
skywalking.log_enable => 0 => 0
skywalking.log_path => /tmp/skywalking-php.log => /tmp/skywalking-php.log
skywalking.version => 8 => 8
```

- gdb core文件

```
[New LWP 20829]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm:'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:241
241	../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) where
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:241
#1  0x00007f1d4bbae79b in sky_request_flush (response=response@entry=0x0) at /tmp/pkg/skywalking/src/sky_module.cc:151
#2  0x00007f1d4bb90406 in zm_deactivate_skywalking (type=<optimized out>, module_number=<optimized out>) at /tmp/pkg/skywalking/skywalking.cc:168
#3  0x0000558eae1df294 in zend_deactivate_modules ()
#4  0x0000558eae1750dd in php_request_shutdown ()
#5  0x0000558eadefad3d in ?? ()
#6  0x00007f1d4ed3a09b in __libc_start_main (main=0x558eadef9f40, argc=1, argv=0x7fff74178a78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff74178a68) at ../csu/libc-start.c:308
#7  0x0000558eadefbb7a in _start ()
```

**Comment by ytbssso** [comment]
just it?

**Comment by heyanlong** [comment]
repairing...

**Comment by tristan-tsl** [comment]
I also encountered this problem

**Comment by heyanlong** [comment]
@tristan-tsl os? php version? skywalking-php version?
