### ISSUE TITLE
服务运行期间产生了很很多core

### ISSUE THREAD

**Issue by newpurr** [SkyAPM/SkyAPM-php-sdk#434]
1. 这个出现的频次最多
```
warning: Can't read pathname for load map: No error information.
Core was generated by `gott-open-search worker                                                       '.
Program terminated with signal SIGBUS, Bus error.
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local (this=0x7f2e81ae0b403142) at /usr/include/c++/9.3.0/bits/basic_string.h:657
657	      ~basic_string()
[Current thread is 1 (LWP 1016)]
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local (this=0x7f2e81ae0b403142) at /usr/include/c++/9.3.0/bits/basic_string.h:657
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7f2e81ae0b403142) at /usr/include/c++/9.3.0/bits/basic_string.h:231
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x7f2e81ae0b403142, __in_chrg=<optimized out>) at /usr/include/c++/9.3.0/bits/basic_string.h:658
#3  CrossProcessBag::~CrossProcessBag (this=0x7f2e81ae0b40300a, __in_chrg=<optimized out>) at /usr/src/php/ext/skywalking/src/cross_process_bag.h:27
#4  Segment::~Segment (this=0x556a5f252460, __in_chrg=<optimized out>) at /usr/src/php/ext/skywalking/src/segment.cc:51
#5  0x00007f2e7fc791c5 in sky_request_flush(_zval_struct*, unsigned long) () at /usr/src/php/ext/skywalking/src/sky_module.cc:208
#6  0x00007f2e7fc76605 in sky_execute_ex(_zend_execute_data*) () at /usr/src/php/ext/skywalking/src/sky_execute.cc:117
#7  0x00007f2e7efd997b in swoole::PHPCoroutine::main_func(void*) () at /usr/src/php/ext/swoole/ext-src/swoole_coroutine.cc:658
#8  0x00007f2e7f04f0fd in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>, this=0x556a5f156520) at /usr/include/c++/9.3.0/bits/std_function.h:683
#9  swoole::coroutine::Context::context_func (arg=0x556a5f156520) at /usr/src/php/ext/swoole/src/coroutine/context.cc:136
#10 0x00007f2e7f0ab871 in make_fcontext () from /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole.so
#11 0x0000000000000000 in ?? ()
```

```
(gdb) bt
#0  0x00007f2e81a715b3 in free () from /lib/ld-musl-x86_64.so.1
#1  0x00007f2e7fc73ff1 in __gnu_cxx::new_allocator<char>::deallocate (this=0x556a5f15a4e8, __p=<optimized out>) at /usr/include/c++/9.3.0/ext/new_allocator.h:119
#2  std::allocator_traits<std::allocator<char> >::deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/9.3.0/bits/alloc_traits.h:470
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x556a5f15a4e8) at /usr/include/c++/9.3.0/bits/basic_string.h:237
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x556a5f15a4e8) at /usr/include/c++/9.3.0/bits/basic_string.h:232
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x556a5f15a4e8, __in_chrg=<optimized out>) at /usr/include/c++/9.3.0/bits/basic_string.h:658
#6  CrossProcessBag::~CrossProcessBag (this=0x556a5f15a3b0, __in_chrg=<optimized out>) at /usr/src/php/ext/skywalking/src/cross_process_bag.h:27
#7  Segment::~Segment (this=0x556a5f227ba0, __in_chrg=<optimized out>) at /usr/src/php/ext/skywalking/src/segment.cc:51
#8  0x00007f2e7fc791c5 in sky_request_flush(_zval_struct*, unsigned long) () at /usr/src/php/ext/skywalking/src/sky_module.cc:208
#9  0x00007f2e7fc76605 in sky_execute_ex(_zend_execute_data*) () at /usr/src/php/ext/skywalking/src/sky_execute.cc:117
#10 0x00007f2e7efd997b in swoole::PHPCoroutine::main_func(void*) () at /usr/src/php/ext/swoole/ext-src/swoole_coroutine.cc:658
#11 0x00007f2e7f04f0fd in std::function<void (void*)>::operator()(void*) const (__args#0=<optimized out>, this=0x556a5f226460) at /usr/include/c++/9.3.0/bits/std_function.h:683
#12 swoole::coroutine::Context::context_func (arg=0x556a5f226460) at /usr/src/php/ext/swoole/src/coroutine/context.cc:136
#13 0x00007f2e7f0ab871 in make_fcontext () from /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole.so
#14 0x0000000000000000 in ?? ()
```

```
/epetphp # gdb php -c core.53346
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.
[New LWP 53346]
[New LWP 53347]
[New LWP 53348]
[New LWP 53349]
[New LWP 53350]

warning: Can't read pathname for load map: No error information.
Core was generated by `gott-open-search worker                                                       '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f2e81a929f3 in setjmp () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 53346)]
(gdb) bt
#0  0x00007f2e81a929f3 in setjmp () from /lib/ld-musl-x86_64.so.1
#1  0x00007f2e81a92b4e in raise () from /lib/ld-musl-x86_64.so.1
#2  0x00007f2e81a93f9d in ?? () from /lib/ld-musl-x86_64.so.1
#3  0x00007f2e81ae30a8 in ?? () from /lib/ld-musl-x86_64.so.1
#4  0x0000000000000000 in ?? ()
```

### debug步骤
```bash
# 1. docker alpine镜像安装gdb
# 2. gdb调试
gdb php -c core.111
> bt
```

**Comment by heyanlong** [comment]
感谢反馈
