### ISSUE TITLE
skywakling导致php命令行终止执行

### ISSUE THREAD

**Issue by stonehun** [SkyAPM/SkyAPM-php-sdk#527]
Program terminated with signal SIGBUS, Bus error.
#0  0x00007f7c83e2104b in boost::interprocess::ipcdetail::atomic_cas32 (cmp=0, with=1, mem=0x7f7c804ee000) at /usr/include/boost/interprocess/detail/atomic.hpp:141
141                             : "cc");
(gdb) bt
#0  0x00007f7c83e2104b in boost::interprocess::ipcdetail::atomic_cas32 (cmp=0, with=1, mem=0x7f7c804ee000) at /usr/include/boost/interprocess/detail/atomic.hpp:141
#1  boost::interprocess::ipcdetail::managed_open_or_create_impl<boost::interprocess::shared_memory_object, 0ul, true, false>::priv_open_or_create<boost::interprocess::ipcdetail::msg_queue_initialization_func_t<boost::interprocess::offset_ptr<void, long, unsigned long, 0ul> > > (this=this@entry=0x7ffca5064130,
    type=type@entry=boost::interprocess::ipcdetail::DoOpenOrCreate, id=@0x7ffca5064128: 0x7f7c9476f800 "skywalking_queue_3313116", size=20996304, mode=mode@entry=boost::interprocess::read_write, addr=addr@entry=0x0, perm=..., construct_func=...) at /usr/include/boost/interprocess/detail/managed_open_or_create_impl.hpp:409
#2  0x00007f7c83e1f49e in boost::interprocess::ipcdetail::managed_open_or_create_impl<boost::interprocess::shared_memory_object, 0ul, true, false>::managed_open_or_create_impl<boost::interprocess::ipcdetail::msg_queue_initialization_func_t<boost::interprocess::offset_ptr<void, long, unsigned long, 0ul> > > (perm=..., construct_func=...,
    addr=0x0, mode=boost::interprocess::read_write, size=<optimized out>, id=@0x7ffca5064128: 0x7f7c9476f800 "skywalking_queue_3313116", this=0x7ffca5064130) at /usr/include/boost/interprocess/detail/managed_open_or_create_impl.hpp:220
#3  boost::interprocess::message_queue_t<boost::interprocess::offset_ptr<void, long, unsigned long, 0ul> >::message_queue_t (perm=..., max_msg_size=<optimized out>, max_num_msg=1024, name=<optimized out>, this=0x7ffca5064130) at /usr/include/boost/interprocess/ipc/message_queue.hpp:683
#4  sky_module_init () at /var/local/git/SkyAPM-php-sdk/src/sky_module.cc:99
#5  0x00007f7c83e00f95 in zm_startup_skywalking (type=<optimized out>, module_number=<optimized out>) at /var/local/git/SkyAPM-php-sdk/skywalking.cc:218
#6  0x000055e9e8ff0dde in zend_startup_module_ex ()
#7  0x000055e9e8ff0e8c in ?? ()
#8  0x000055e9e8ffe44a in zend_hash_apply ()
#9  0x000055e9e8ff113a in zend_startup_modules ()
#10 0x000055e9e8f8aab3 in php_module_startup ()
#11 0x000055e9e90813dd in ?? ()
#12 0x000055e9e8c80061 in ?? ()
#13 0x00007f7c91e7b2e1 in __libc_start_main (main=0x55e9e8c7fed0, argc=6, argv=0x7ffca5065968, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffca5065958) at ../csu/libc-start.c:291
#14 0x000055e9e8c8047a in _start ()

**Comment by heyanlong** [comment]
5.0.1版本试一下
